### ISSUE TITLE
Questions about inter-Grav communication

### ISSUE THREAD

**Issue by lePereT** [suborbital/grav#81]
Hi Grav team. Is there any documentation or description of how messaging internally (in process) interacts with messaging using transports? For example do we just get one big bus or can we set filtering so that only a subset of messages move across the mesh/bridge?

I'm reading the source but I can't get a feel of how flexible the overall architecture of a Grav mesh might be, how topic hygiene, security, authentication and authorisation might be introduced, and so on. Apologies for the very general questions it would be great to have a clearer picture!

**Comment by cohix** [comment]
Hey @lePereT !

The basic answer is that:
- Incoming messages from any connection get sent to the bus, and then any listening pods receive it (unless they're using `OnType` or similar)
- Messages sent by any pod get sent to every mesh connection, and any bridge connection where msgType == connection topic (bridge connections are topic-specific)

As for the rest, you can use `belongsTo`, `interests` and `capabilities` to do some basic routing, but there isn't much in terms of built-in authn/authz since we usually consider that an application-level concern. You can delegate some of that to a message broker if you're using bridge connections.

Hope that answers your questions!

**Comment by lePereT** [comment]
Great, thanks @cohix!
